# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install dependencies in the agent pool server to make the system ready for build generation process
- script: |
    sudo apt-get update
    sudo apt-get -y install build-essential gcc-arm-none-eabi cmake ninja-build
  displayName: "Install dependencies"
  
- script: |
    cmake -G "Ninja" -Bbuild . -DCMAKE_TOOLCHAIN_FILE=cmake/stm32l4.cmake
    cmake --build build
  displayName: "Build the software"
